------------------------------------------------------------------------
-- This file holds all global (not zone specific) text references
------------------------------------------------------------------------
tpz = tpz or {}
tpz.msg = tpz.msg or {}

------------------------------------
-- Message Channels
------------------------------------

tpz.msg.channel =
{
    SAY            = 0,
    SHOUT          = 1,
    TELL           = 3,
    PARTY          = 4,
    LINKSHELL      = 5,
    SYSTEM_1       = 6, -- Standard "PrintToPlayer" default if no type specified
    SYSTEM_2       = 7, -- Login / world announcement messages
    EMOTION        = 8,
    -- 9 / 10 / 11 = Does not work / nothing
    GM_PROMPT      = 12, -- Menu prompt from GM
    NS_SAY         = 13, -- Same as MESSAGE_SAY but has no speaker object displayed
    NS_SHOUT       = 14, -- Same as MESSAGE_SHOUT but has no speaker object displayed
    NS_PARTY       = 15, -- Same as MESSAGE_PARTY but has no speaker object displayed
    NS_LINKSHELL   = 16, -- Same as MESSAGE_LINKSHELL but has no speaker object displayed
    UNKNOWN_17     = 17, -- 17 through 25 appear to repeat the effects of other values
    UNKNOWN_18     = 18,
    UNKNOWN_19     = 19,
    UNKNOWN_20     = 20,
    UNKNOWN_21     = 21,
    UNKNOWN_22     = 22,
    UNKNOWN_23     = 23,
    UNKNOWN_24     = 24,
    UNKNOWN_25     = 25,
    YELL           = 26,
    LINKSHELL2     = 27, -- Second LS color...Default is Green
    NS_LINKSHELL2  = 28, -- Same as LINKSHELL_2 but has but has no speaker object displayed
    SYSTEM_3       = 29, -- "Basic system messages" in config menu. Yellow by default.
    LINKSHELL3     = 30, -- Yes really it looks like a 3rd LS may have been planned at some point.
    NS_LINKSHELL3  = 31, -- (assumed as it follows pattern and color)
    UNKNOWN_32     = 32, -- Looks the same as 31
    UNITY          = 33
}

-- used by PrintToArea
tpz.msg.area =
{
    SYSTEM      = 0, -- Server wide like the purple stuff :)
    SAY         = 1, -- Will display in small area around player
    SHOUT       = 2, -- Will display in wide area around player
    PARTY       = 3, -- Will display to players entire party/alliance
    YELL        = 4  -- If yell is enabled in zone, will display.
}

------------------------------------
-- Basic Messages
------------------------------------

tpz.msg.basic =
{
    NONE    = 0, -- Display nothing
    HIT_DMG = 1, -- <actor> hits <target> for <amount> points of damage.

    -- Magic
    MAGIC_DMG              = 2,   -- <caster> casts <spell>. <target> takes <amount> damage.
    MAGIC_RECOVERS_HP      = 7,   -- <caster> casts <spell>. <target> recovers <amount> HP.
    MAGIC_UNABLE_TO_CAST   = 17,  -- Unable to cast spells at this time.
    MAGIC_UNABLE_TO_CAST_2 = 18,  -- Unable to cast spells at this time.
    MAGIC_CANNOT_CAST      = 47,  -- <caster> cannot cast <spell>.
    MAGIC_CANNOT_BE_CAST   = 48,  -- <spell> cannot be cast on <target>. (example: tractor)
    MAGIC_NO_EFFECT        = 75,  -- <caster>'s <spell> has no effect on <target>.
    MAGIC_REMOVE_EFFECT    = 83,  -- <caster> casts <spell>. <caster> successfully removes <target>'s <status>.
    MAGIC_RESIST           = 85,  -- <caster> casts <spell>. <target> resists the spell.
    MAGIC_TELEPORT         = 93,  -- <caster> casts <spell>. <target> vanishes.
    MAGIC_FAIL             = 114, -- <caster> casts <spell> on <target>, but the spell fails to take effect
    MAGIC_RESIST_2         = 284, -- <target> resists the effects of the spell!
    MAGIC_DRAIN_HP         = 227, -- <caster> casts <spell>. <amount> HP drained from <target>.
    MAGIC_DRAIN_MP         = 228, -- <caster> casts <spell>. <amount> MP drained from <target>.
    MAGIC_GAIN_EFFECT      = 230, -- <caster> casts <spell>. <target> gains the effect of <status>.
    MAGIC_ENFEEB_IS        = 236, -- <caster> casts <spell>. <target> is <status>.
    MAGIC_ENFEEB           = 237, -- <caster> casts <spell>. <target> receives the effect of <status>.
    MAGIC_CASTS_ON         = 309, -- <caster> casts <spell> on <target>.
    MAGIC_ABSORB_STR       = 329, -- <caster> casts <spell>. <target>'s STR is drained.
    MAGIC_ABSORB_DEX       = 330, -- <caster> casts <spell>. <target>'s DEX is drained.
    MAGIC_ABSORB_VIT       = 331, -- <caster> casts <spell>. <target>'s VIT is drained.
    MAGIC_ABSORB_AGI       = 332, -- <caster> casts <spell>. <target>'s AGI is drained.
    MAGIC_ABSORB_INT       = 333, -- <caster> casts <spell>. <target>'s INT is drained.
    MAGIC_ABSORB_MND       = 334, -- <caster> casts <spell>. <target>'s MND is drained.
    MAGIC_ABSORB_CHR       = 335, -- <caster> casts <spell>. <target>'s CHR is drained.
    MAGIC_ERASE            = 341, -- <caster> casts <spell>. <target>'s <status> effect disappears!
    MAGIC_STEAL            = 430, -- <caster> casts <spell>. 1 of <target>'s effects is drained.
    MAGIC_TP_REDUCE        = 431, -- <caster> casts <spell>. <target>'s TP is reduced.
    MAGIC_ABSORB_TP        = 454, -- <caster> casts <spell>. <amount> TP drained from <target>.
    MAGIC_ABSORB_ACC       = 533, -- <caster> casts <spell>. <target>'s Accuracy is drained.
    MAGIC_ABSORB_AILMENT   = 572, -- <caster> casts <spell>. <caster> absorbs <number> of <target>'s status ailments.
    MAGIC_MUST_ASTRAL_FLOW = 581, -- Unable to cast <spell>. Astral Flow must be in effect to cast this spell.

    -- Weaponskill / Mobskill (0-255 WS, 256+ monster skill)
    SKILL_RECOVERS_MP      = 224, -- <user> uses <skill>. <target> recovers <amount> MP.
    SKILL_RECOVERS_HP      = 103, -- The <player> uses .. <target> recovers .. HP.
    SELF_HEAL              = 238, -- <user> uses <skill>. <user> recovers <amount> HP.
    SELF_HEAL_SECONDARY    = 263, -- <target> recovers <amount> HP.
    AOE_REGAIN_HP          = 357, -- <target> regains <amount> HP.
    AOE_REGAIN_MP          = 358, -- <target> regains <amount> MP.
    SKILL_ERASE            = 159, -- <user> uses <skill> <target>'s <status> effect disappears!
    DAMAGE                 = 185, -- <user> uses <skill>, <target> takes <number> damage. DEFAULT
    DAMAGE_SECONDARY       = 264,
    SKILL_DRAIN_HP         = 187, -- <user> uses <skill>. <amount> HP drained from <target>
    SKILL_DRAIN_MP         = 225, -- <user> uses <skill>. <amount> MP drained from <target>
    SKILL_DRAIN_TP         = 226, -- <user> uses <skill>. <amount> TP drained from <target>
    SKILL_GAIN_EFFECT      = 186, -- <user> uses <skill>. <target> gains the effect of <status>.
    SKILL_MISS             = 188, -- <user> uses <skill>, but misses <target>.
    SKILL_NO_EFFECT        = 189, -- <user> uses <skill>. No effect on <target>.
    SKILL_ENFEEB_IS        = 242, -- <user> uses <skill>. <target> is <status>.
    SKILL_ENFEEB           = 243, -- <user> uses <skill>. <target> receives the effect of <status>.
    SKILL_ENFEEB_2         = 142, -- <user> uses <skill>. <target> receives the effect of <status> and <status>.
    ABILITIES_RECHARGED    = 360, -- <user> uses <skill>. All of <target>'s abilities are recharged.

    -- Job Ability messages
    JA_RECOVERS_HP         = 102, -- The <player> uses .. <target> recovers .. HP.
    JA_RECOVERS_MP         = 451, -- <user> uses <ability>. <target> regains <amount> MP.
    USES_JA                = 100, -- The <player> uses ..
    USES                   = 101, -- The <entity> uses ..
    USES_JA_TAKE_DAMAGE    = 317, -- The <player> uses .. <target> takes .. points of damage.
    JA_DAMAGE              = 110, -- <user> uses <ability>. <target> takes <amount> damage.
    JA_ENFEEB_IS           = 127, -- <user> uses <ability>. <target> is <status>.
    JA_REMOVE_EFFECT       = 123, -- <user> uses <ability>. <user> successfully removes <target>'s <status>.
    JA_REMOVE_EFFECT_2     = 321, -- <user> uses <ability>. <target>'s <status> wears off.
    JA_NO_EFFECT           = 156, -- <user> uses <ability>. No effect on <target>. (1 line msg)
    JA_NO_EFFECT_2         = 323, -- <user> uses <ability>. No effect on <target>. (2 line msg)
    JA_MISS                = 158, -- <user> uses <ability>, but misses. (no name included)
    JA_MISS_2              = 324, -- <user> uses <ability>, but misses <target>. (includes target name)

    -- Misc other unsorted (sort me)
	-- STARTS_CASTING         = 3, -- <name> starts casting <spell>.
    DEFEATS_TARG           = 6,   -- The <player> defeats <target>.
	-- GAINS_EXP              = 8, -- <name> gains <amount> experience point(s).
	-- LEVEL_UP               = 9, -- <name> attains level <value>.
	-- LOSES_EXP              = 10, -- <name> loses <value> experience point(s).
	-- LEVEL_DOWN             = 11, -- <name> falls to level <value>
    ALREADY_CLAIMED        = 12,  -- Cannot attack. Your target is already claimed.
	-- COUNTER_ABSORB         = 14, -- <attacker>'s attack is countered by <defender>. <number> of <attacker>'s shadows absorb the damage and disappear.
	NORMAL_MISS            = 15, -- <attacker> misses <target>.
    IS_INTERRUPTED         = 16,  -- <caster>'s casting is interrupted.
	-- CALL_FOR_HELP          = 19, -- <name> calls for help!
    FALL_TO_GROUND         = 20,  -- <name> falls to the ground.
	-- NO_EXP_GAINED          = 21, -- No experience points gained.
	-- CANT_CALL_FOR_HELP     = 22, -- You cannot call for help at this time.
	-- LEARN_NEW_SPELL        = 23, -- <name> learns a new spell!
    IS_PARALYZED           = 29,  -- The <player> is paralyzed.
    ANTICIPATE             = 30,  -- <name> anticipates the attack.
    SHADOW_ABSORB          = 31,  -- <number> of <target>'s shadows absorb the damage and disappear.
	DODGE                  = 32,  -- <name> dodges the attack.
	COUNTER_DAMAGE         = 33,  -- <attacker>'s attack is countered by <defender>. <attacker> takes <number> points of damage.
    NOT_ENOUGH_MP          = 34,  -- <name> does not have enough MP to cast <spell>.
    NO_NINJA_TOOLS         = 35,  -- <name> lacks the ninja tools to cast <spell>.
	-- TOO_FAR_EXP            = 37, -- You are too far from the battle to gain experience.
	-- SKILL_UP               = 38, -- <name>'s <weapon> skill rises <number> points.
	-- NEED_DUAL_WIELD        = 39, -- You need the Dual Wield ability to equip the <item> as a sub-weapon.
	-- CANT_USE_SPELL_AREA    = 40, -- You cannot use <spell> in this area.
	-- MAGIC_CASTS_ON_2       = 42, -- <caster> casts <spell> on <target>.
	-- LEARN_WS               = 45, -- <name> learns "<weaponskill>"!
    UNABLE_TO_CAST_SPELLS  = 49,  -- The <player> is unable to cast spells.
	-- GAIN_MERIT             = 50, -- <name> earns a merit point! (Total: <number>)
	-- SKILL_LEVEL_UP         = 53, -- <name>'s <skill> reaches level <number>.
	MELEE_MISS             = 63, -- <name> misses <target>.
	-- IS_NO_LONGER_STATUS_2  = 64, -- <name> is no longer <status>.
	-- CRIT_HIT               = 67, -- <name> scores a critical hit! <target> takes <number> damage.
	-- SHIELD_BLOCK           = 69, -- <defender> blocks the <attacker>'s attack with his shield.
	-- PARRIES                = 70, -- <defender> parries the <attacker>'s attack with his weapon.
    CANNOT_PERFORM         = 71,  -- The <actor> cannot perform that action.
    CANNOT_PERFORM_TARG    = 72,  -- That action cannot be performed on <target>.
	-- NO_AOE_TARGET          = 76, -- No valid target within area of effect.
	-- USES_SANGE             = 77, -- <name> uses Sange. <target> takes <number> point(s) of damage.
	-- MAGIC_CAST_STATUS      = 82, -- <name> casts <spell>. <target> is <status>!
	-- STATUS_TAKES_EFFECT    = 84, -- <target> is <status>.
	-- OUTSIDE_AOE            = 86, -- <caster> casts <spell>, but <target> is outside the area of effect.
    UNABLE_TO_USE_JA       = 87,  -- Unable to use job ability.
    UNABLE_TO_USE_JA2      = 88,  -- Unable to use job ability.
	-- UNABLE_TO_WS           = 89, -- Unable to use weaponskill.
	-- UNABLE_TO_WS_2         = 90, -- Unable to use weaponskill.
    WAIT_LONGER            = 94,  -- You must wait longer to perform that action.
	-- CANNOT_LEARN_SPELL     = 95, -- You cannot learn <spell>. You do not meet the job or level requirements.
	-- ALREADY_KNOW_SPELL     = 96, -- You already know <spell>.
	-- DEFEATED               = 97, -- <defender> was defeated by <attacker>.
	-- GAINS_EXP_2            = 105, -- <name> gains <amount> experience point(s).
	IS_INTIMIDATED         = 106, -- The <player> is intimidated by <target>'s presence.
    FAMILIAR_PC            = 108, -- The <player> uses .. Pet's powers increase!
    FAMILIAR_MOB           = 109, -- The <mob> uses .. Pet's powers increase!
	-- DOOM_COUNTER           = 112 -- <name>'s doom counter is now down to <number>.
	-- CAST_FALL_GROUND       = 113, -- <caster> casts <spell>. <target> falls to the ground.
	-- JA_ATK_UP_DEF_DN       = 115, -- <user> uses <ability>. Attacks are enhanced but defense weakens.
	-- JA_ATK_ENH             = 116, -- <user> uses <ability>. <user>'s attacks are enhanced.
	-- JA_DEF_UP_ATK_DN       = 117, -- <name> uses <ability>. Defense is enhanced but attacks weaken.
	-- JA_ACC_UP_EVA_DN       = 118, -- <name> uses <ability>. Accuracy is enhanced but evasion is impaired.
	-- JA_USE_TARGET          = 119, -- <name> uses <ability> on <target>.
	-- JA_TARGET_ACC_UP       = 120, -- <name> uses <ability>. <target>'s accuracy is enhanced.
	-- JA_TARGET_EVA_UP       = 121, -- <name> uses <ability>. <target>'s evasion is enhanced.
	-- JA_TARGET_HP_REC       = 122, -- <name> uses <ability>. <target> recovers <number> HP.
	-- GATE_BREACH            = 124, -- <name> achieves Gate Breach status!
	STEAL_SUCCESS          = 125, -- <user> uses <ability>. <user> steals <item> from <target>.
	-- JA_MOVE_SPD            = 126, -- <name> uses <ability>. <name>'s movement speed increases.
	-- JA_STUN                = 127, -- <name> uses <ability>. <target> is stunned.
	-- WEAKENED               = 128, -- <user> is weakened and cannot perform that action.
	MUG_SUCCESS            = 129, -- <user> uses <ability>. <user> mugs <amount> gil from <target>.
	-- WEAKENED_EQUIP         = 130, -- <user> is weakened for making an equipment change.
	-- JA_FORTIFY_UNDEAD      = 131, -- <user> uses <ability>. <target> is fortified against undead.
	-- STEAL_PETRAS           = 133, -- <user> uses <ability>. <user> steals <number> Petras from <target>.
	-- JA_FORTIFY_ARCANA      = 134, -- <user> uses <ability>. <target> is fortified against arcana.
	-- USE_WEAPONSKILL        = 135, -- <user> uses <weaponskill> on <target>.
	-- CHARM                  = 136, -- <user> uses <ability>. <target> is now under <user>'s control.
	-- CHARM_FAIL             = 137, -- <user> uses <ability>. <user> fails to charm <target>.
	-- TAME                   = 138, -- <user> uses <ability>. <target> seems friendlier.
	-- SCAVENGE_FAIL          = 139, -- <user> uses <ability>, but finds nothing.
	-- SCAVENGE_SUCCESS       = 140, -- <user> uses <ability>, and finds a <item>.
	-- JA_STUN_2              = 141, -- <user> uses <ability>. <target> is stunned.
	-- WS_ACC_DN_EVA_DN       = 142, -- <user> uses <weaponskill>. <target> receives the effect of Accuracy Down and Evasion Down.
	-- SHARPSHOT              = 143, -- <user> uses <ability>. Ranged attacks become more accurate.
	-- JA_ACC_DN_EVA_DN       = 144, -- <user> uses <ability>. <target> receives the effect of Accuracy Down and Evasion Down.
	-- ACC_DN_EVA_DN          = 145, -- <target> receives the effect of Accuracy Down and Evasion Down.
	-- JA_ACC_UP_EVA_UP       = 146, -- <user> uses <ability>. <target> receives the effect of Accuracy Boost and Evasion Boost.
	-- ACC_UP_EVA_UP          = 147, -- <target> receives the effect of Accuracy Boost and Evasion Boost.
	-- JA_FORTIFY_DEMON       = 148, -- <user> uses <ability>. <target> is fortified against demons.
	-- FORTIFY_DEMON          = 149, -- <target> is fortified against demons.
	-- JA_FORTIFY_DRAGON      = 150, -- <user> uses <ability>. <target> is fortified against dragons.
	-- FORTIFY_DRAGON         = 151, -- <target> is fortified against dragons.
	STEAL_FAIL             = 153, -- <user> uses <ability>. <user> fails to steal from <target>.
	-- TARG_OUT_OF_RANGE_2    = 154, -- <target> is out of range.
	CANNOT_ON_THAT_TARG    = 155, -- You cannot perform that action on the specified target.
	-- BARRAGE                = 157, -- <user> uses Barrage. <target> takes <number> points of damage.
	-- CHECK_HIGH_EVA_DEF     = 170, -- <name> seems <difficulty>. It seems to have high evasion and defense.
	-- CHECK_HIGH_EVA         = 171, -- <name> seems <difficulty>. It seems to have high evasion.
	-- CHECK_HIGH_EVA_LOW_DEF = 172, -- <name> seems <difficulty>. It seems to have high evasion but low defense.
	-- CHECK_HIGH_DEF         = 173, -- <name> seems <difficulty>. It seems to have high defense.
	-- CHECK_EVEN             = 174, -- <name> seems <difficulty>.
	-- CHECK_LOW_DEF          = 175, -- <name> seems <difficulty>. It seems to have low defense.
	-- CHECK_HIGH_DEF_LOW_EVA = 176, -- <name> seems <difficulty>. It seems to have low evasion but high defense.
	-- CHECK_LOW_EVA          = 177, -- <name> seems <difficulty>. It seems to have low evasion.
	-- CHECK_LOW_EVA_DEF      = 178, -- <name> seems <difficulty>. It seems to have low evasion and low defense.
	-- UNABLE_USE_WEAPONSKILL = 191, -- <user> is unable to use weapon skills.
	-- CANNOT_USE_VS_TARGET   = 193, -- <skill> cannot be used against that target.
	-- SKILL_GAIN_STATUS      = 194, -- <user> uses <skill>. <target> gains the effect of <status>.
	-- SKILLCHAIN             = 196, -- Skillchain! <target> takes <number> point(s) of damage.
	-- SKILL_RESIST           = 197, -- <user> uses <skill>, but <target> resists. <target> takes <number> point(s) of damage.
	-- TOO_FAR_AWAY_2         = 198, -- <target> is too far away.
	REQUIRES_SHIELD        = 199, -- That action requires a shield.
	
	-- = 219, -- You cannot see <target>.
	-- = 220, -- You move and interrupt your aim.
	-- = 221, -- <user> uses <ability>. <user>'s pet is released.
	-- = 222, -- <target> isn't selling anything.
	-- = 223, -- Skillchain: <number> points of damage.
	-- = 229, -- Additional effect: <target> takes <number> additional points of damage.
	DISAPPEAR_NUM          = 231, -- <num> of <target>'s effects disappear!
	-- = 232, -- <target> is drawn in!
	-- = 233, -- You are ineligible to attack that target.
	-- = 234, -- Auto-targeting <target>.
	-- = 239, -- Size: <number>
	-- = 240, -- The <user> tries to hide, but is spotted by <actor>.
	-- = 241, -- <user> hides!
	MUG_FAIL               = 244, -- <user> fails to mug <target>.
	-- = 245, -- The <user> uses Eagle Eye Shot, but misses <target>.
	-- = 248, -- <user>'s attack has no effect on <target>.
	-- = 249, -- <target>'s strength is impossible to gauge!
	-- = 250, -- Reraise takes effect!
	-- = 252, -- <caster> casts <spell>. Magic Burst! <target> takes <number> point(s) of damage.
	-- = 253, -- EXP chain #<number>! <target> gains <number> experience point(s).
	-- = 254, -- Current enmity: <number>
	-- = 255, -- DEBUG: <user>><number>% chance of success.
	-- = 256, -- In this flower pot: Seeds sown: <item>
	-- = 257, -- Crystal used: none
	-- = 258, -- Crystal used: <item>
	-- = 259, -- First crystal used: <item> Second crystal used: <item>
	-- = 260, -- First crystal used: none Second crystal used: <item>
	-- = 261, -- First crystal used: <item> Second crystal used: none
	-- = 262, -- First crystal used: none Second crystal used: none
	-- = 265, -- Magic Burst! <target> takes <number> point(s) of damage.
	-- = 266, -- <target> gains the effect of <status>.
	-- = 267, -- <target> receives the effect of <status>.
	-- = 268, -- <caster> casts <spell>. Magic Burst! <target> receives the effect of <status>.
	-- = 269, -- Magic Burst! <target> receives the effect of <status>.
	-- = 270, -- <target> is <status>.
	-- = 271, -- <caster> casts <spell>. Magic Burst! <target> is <status>.
	-- = 272, -- Magic Burst! <target> is <status>.
	-- = 273, -- <player> vanishes!
	-- = 274, -- <caster> casts <spell>. Magic Burst! <number> HP drained from <target>.
	-- = 275, -- <caster> casts <spell>. Magic Burst! <number> MP drained from <target>.
	-- = 276, -- <player> recovers <number> mp.
	IS_EFFECT              = 277, -- <player> is <status>.
	-- = 278, -- <player> receives the effect of <status>.
	-- = 279, -- <player> is <status>.
	-- = 280, -- <player> is <status>.
	-- = 281, -- <number> HP is drained from <player>.
	EVADES                 = 282, -- <player> evades.
	NO_EFFECT              = 283, -- No effect on <player>.
	-- = 285, -- <player>'s attacks are enhanced.
	-- = 286, -- <player> is fortified against undead.
	-- = 287, -- <player> is fortified against arcana.
	-- = 288, -- Skillchain: Light. <player> takes <number> point(s) of damage.
	-- = 289, -- Skillchain: Darkness. <player> takes <number> point(s) of damage.
	-- = 290, -- Skillchain: Gravitation. <player> takes <number> point(s) of damage.
	-- = 291, -- Skillchain: Fragmentation. <player> takes <number> point(s) of damage.
	-- = 292, -- Skillchain: Distortion. <player> takes <number> point(s) of damage.
	-- = 293, -- Skillchain: Fusion. <player> takes <number> point(s) of damage.
	-- = 294, -- Skillchain: Compression. <player> takes <number> point(s) of damage.
	-- = 295, -- Skillchain: Liquefaction. <player> takes <number> point(s) of damage.
	-- = 296, -- Skillchain: Induration. <player> takes <number> point(s) of damage.
	-- = 297, -- Skillchain: Reverberation. <player> takes <number> point(s) of damage.
	-- = 298, -- Skillchain: Transfixion. <player> takes <number> point(s) of damage.
	-- = 299, -- Skillchain: Scission. <player> takes <number> point(s) of damage.
	
	-- = 300, -- Skillchain: Detonation. <target> takes <number> point(s) of damage.
	-- = 302, -- Skillchain: Cosmic Elucidation. <target> takes <number> point(s) of damage.
	-- = 303, -- <user> uses Divine Seal.
	-- = 304, -- <user> uses Elemental Seal.
	-- = 305, -- <user> uses Trick Attack.
	-- = 306, -- <user> uses <ability>. <target> recovers <number> HP. (Blue text)
	NEEDS_2H_WEAPON        = 307, -- That action requires a two-handed weapon.
	-- = 310, -- <user>'s <weapon> skill drops 0.<number> points!
	-- = 313, -- <player> is out of range. Unable to cast <spell>.
	-- = 314, -- <player>'s level is currently restricted to <number>. Equipment affected by the level restriction will be adjusted accordingly.
	CANT_BE_USED_IN_AREA   = 316, -- That action cannot be used in this area.
	-- = 318, -- <user> uses <ability>. <player> recovers <number> HP. (Blue text)
	-- = 319, -- <user> uses <ability. <player> gains the effect of <status>.
	-- = 320, -- <user> uses <skill>. <target> receives the effect of <status>.
	-- = 322, -- <user> uses <ability>. <player>s' <status> effect wears off.
	-- = 325, -- You are charmed by an enemy and unable to act.
	-- = 326, -- <user> readies <ability>.
	-- = 327, -- <caster> starts casting <spell> on <target>.
	-- = 328, -- <target> is too far away.
	-- = 336, -- No effect on that pet.
	-- = 337, -- You do not have the necessary item equipped to call a beast.
	-- = 338, -- You cannot summon avatars here.
	-- = 339, -- Your mount senses a hostile presence and refuses to come to your side.
	-- = 340, -- You must equip your main weapon first to use Dual Wield.
	-- = 342, -- <caster> casts <spell>. <player>'s <status> effect disappears!
	-- = 343, -- <player>'s <status> effect disappears!
	-- = 344, -- <player>'s <status> effect disappears!
	-- = 345, -- You cannot heal while you have an avatar summoned.
	-- = 346, -- You must summon an avatar to use that command.
	-- = 348, -- You cannot call wyverns here.
	-- = 349, -- You cannot call beasts here.
	-- = 350, -- <actor> is no longer weakened.
	-- = 351, -- The remedy removes <user>'s status ailments.
	-- = 352, -- <user>'s ranged attack hits <target> for <number> point(s) of damage.
	-- = 353, -- <user>'s ranged attack scores a critical hit! <target> takes <number> points of damage.
	-- = 354, -- <user>'s ranged attack misses.
	-- = 355, -- <user>'s ranged attack has no effect on <target>.
	FULL_INVENTORY         = 356, --  Cannot execute command. Your inventory is full.
	NARROWLY_ESCAPE        = 359, -- <name> narrowly escapes impending doom.
	-- = 360, -- <user> uses <skill>. All of <target>'s abilities are recharged.
	TP_REDUCED             = 362, -- <user> uses <skill>. <target>'s TP is reduced to <number>.
	-- = 363, -- <target>'s TP is reduced to <number>.
	-- = 364, -- <user> uses <skill>. All of <target>'s status paramaters are boosted.
	-- = 365, -- All of <target>'s status parameters are boosted.
	MP_DRAINED             = 366, -- <number> MP drained from <target>.
	AOE_HP_RECOVERY        = 367, -- <target> recovers <amount> HP.
	-- = 368, -- <actor> earns a merit point! (Total: <number)
	ATTR_DRAINED           = 369, -- <user> uses <skill>. <number> of <target>'s attributes is drained.
	EFFECT_DRAINED         = 370, -- <user> uses <skill>. <number> status effect is drained from <target>.
	-- = 371, -- <actor> gains <number> limit point(s).
	-- = 372, -- Limit Chain #<number>! <player> gains <number> limit points.
	-- = 373, -- <attacker> hits <defender>. <defender> recovers <number> hit points!
	SWIPE_LUNGE_MB         = 379, -- <user> uses <ability>. Magic Burst! <defender> takes <number> point(s) of damage.
	-- = 380, -- BUGGED? Prevents other messages?
	-- = 381, -- BUGGED? Prevents other messages?
	-- = 382, -- <attacker>'s ranged attack hits <defender>. <defender> recovers <number> hit points!
	-- = 385, -- Skillchain: Light. <target> recovers <number> hit points!
	-- = 386, -- Skillchain: Darkness. <target> recovers <number> hit points!
	-- = 387, -- Skillchain: Gravitation. <target> recovers <number> hit points!
	-- = 388, -- Skillchain: Fragmentation. <target> recovers <number> hit points!
	-- = 389, -- Skillchain: Distortion. <target> recovers <number> hit points!
	-- = 390, -- Skillchain: Fusion. <target> recovers <number> hit points!
	-- = 391, -- Skillchain: Compression. <target> recovers <number> hit points!
	-- = 392, -- Skillchain: Liquefaction. <target> recovers <number> hit points!
	-- = 393, -- Skillchain: Induration. <target> recovers <number> hit points!
	-- = 394, -- Skillchain: Reverberation. <target> recovers <number> hit points!
	-- = 395, -- Skillchain: Transfixion. <target> recovers <number> hit points!
	-- = 396, -- Skillchain: Scission. <target> recovers <number> hit points!
	-- = 397, -- Skillchain: Detonation. <target> recovers <number> hit points!
	-- = 398, -- Skillchain: Impaction. <target> recovers <number> hit points!
	-- = 399, -- <user> uses an <item>. All of <player>'s Petras vanish!
	
	-- = 400, -- <user> uses a <item>. <number> of <target>'s status ailments disappears!
	-- = 401, -- <user> uses a <item>. <number> of <target>'s effects disappear!
	-- = 402, -- <user> uses <skill>. <target>'s magic defense is enhanced.
	-- = 403, -- <number> of <target>'s attributes are drained.
	STATUS_DRAIN           = 404, -- <number> status effects are drained from <target>.
	-- = 405, -- <user> uses <skill>. <number> of <target>'s effects disappear!
	-- = 406, -- <user> uses <skill>. <target> falls to the ground.
	-- = 407, -- <user> uses a <item>. <target>'s TP is reduced
	-- = 408, -- <user> uses a <item>. No effect on <target>.
	TP_INCREASE            = 409, -- <user> uses <skill>. <target>'s TP is increased to <number>.
	-- = 410, -- No target available. Unable to use item.
	-- = 411, -- <user> attempts to use the <item>, but lacks the required number of Ballista Points. You currently have <number> Ballista Points.
	-- = 412, -- <user> uses an <item>. <target> receives the effect of <status>.
	-- = 413, -- <user> uses an <item>. <target> takes <number> point(s) of damage.
	-- = 414, -- <user> uses <ability>. <target> receives the effect of Magic Attack Boost and Magic Defense Boost.
	-- = 415, -- <target> receives the effect of Magic Attack Boost and Magic Defense Boost.
	-- = 416, -- <user> uses <skill>. <target> receives the effect of Magic Attack Boost and Magic Defense Boost.
	-- = 417, -- <user> uses <ability>. <number> of <target>'s attributes are drained.
	-- = 418, -- <user> uses <skill> on <target>. <target>'s target switches to <user>!
	-- = 432, -- <caster> casts <spell>. <target> receives the effect of Accuracy Boost and Evasion Boost.
	-- = 433, -- <caster> casts <spell>. <target> receives the effect of Magic Attack Boost and Magic Defense Boost.
	-- = 434, -- You cannot customize and activated automaton.
	-- = 435, -- <user> uses <ability>! <target>'s abilities are recharged.
	-- = 436, -- <target>'s abilities are recharged.
	-- = 437, -- <user> uses <ability>! <target>'s abilities are recharged. <target>'s TP is increased.
	-- = 438, -- <target>'s abilities are recharged. <target>'s TP is increased.
	-- = 439, -- <user> uses <ability>! All of <target>'s abilities are recharged. <target> regains MP.
	-- = 440, -- All of <target>'s abilities are recharged. <target> regains MP.
	-- = 441, -- <user> uses <ability>. <target> receives the effect of <status>.
	-- = 442, -- <user> learns a new ability!
	-- = 443, -- You cannot learn <ability>. You do not meet the job or level requirements.
	-- = 444, -- You already know <ability>.
	-- = 445, -- You cannot use items at this time.
	CANNOT_ATTACK_TARGET   = 446, -- You cannot attack that target.
	-- = 447, -- You are provoked and unable to change your target.
	-- = 450, -- WATCH1 <player>:<number>
	-- = 452, -- <user> uses <ability>. <target> regains <number> TP.
	STEAL_EFFECT           = 453, -- <user> uses <ability>. <user> steals the effect of <status> from <target>.
	-- = 455, -- Debug : Fishing skill check: <item> : KANJI<number>
	-- = 456, -- Debug : Level Restriction on. PetType <number>/ID <number
	-- = 457, -- Debug : Level Restriction off. PetType <number>/ID <number
	-- = 458, -- Debug : Dif - Now > <number>  RATE <number>/1000
	-- = 459, -- Self-destruct check: skipping calculation of <user>'s self-destruct process md_no<number>/cmd_arg<number> !
	-- = 460, -- EXP Check: <target> > <player> XP:<number>/LvUp<number>
	-- = 477, -- Unable to target <target>. You have not received the level cap status.
	-- = 512, -- You must have a two-handed weapon equipped in the main weapon slot in order to equip a grip.
	-- = 513, -- This grip is not compatible with the two-handed weapon you currently have equipped.
	-- = 514, -- You do not have the proper items equipped to use the <item>.
	-- = 515, -- <user> has successfully recorded the target's image onto an <item>.
	-- = 516, -- <user> was unable to capture the target's image.
	-- = 517, -- The <item> cannot be used on that target.
	-- = 518, -- The <item> cannot be used while under the effect of Invisible or Sneak.
	-- = 519, -- <user> uses <ability>. <target> is afflicted with Lethargic Daze (lv.<number).
	-- = 520, -- <user> uses <ability>. <target> is afflicted with Sluggish Daze (lv.<number>).
	-- = 521, -- <user> uses <ability>. <target> is afflicted with Weakened Daze (lv.<number>).
	-- = 522, -- <user> uses <ability>. <target> takes <number> point(s) of damage and is stunned.
	REQUIRES_COMBAT        = 525, -- <action> can only be performed during battle.
	-- = 526, -- <user> uses <ability>. Enmity is stolen from <target>.
	-- = 527, -- <user> uses <ability>. Ranged attack power and speed are increased. Melee attack power and speed are reduced.
	-- = 528, -- <user> uses <ability>. Enmity is transferred to the <user>'s pet.
	-- = 529, -- <user> uses <ability>. <target> is chainbound.
	-- = 530, -- <actor>'s petrification counter is now down to <number>.
	-- = 531, -- <player> is no longer <status>.
	-- = 534, -- <caster> casts <spell>. <target>'s Attack is drained.
	-- = 535, -- <defender> retaliates. <number> of <attacker>'s shadows absorb the damage and disappear.
	-- = 536, -- <defender> retaliates. <attacker> takes <number> point(s) of damage.
	-- = 537, -- <target>'s TP is increased to <number>%.
	-- = 538, -- A protective energy absorbs the malice of your enemy.
	-- = 539, -- <user> uses <skill>. <target> regains HP.
	-- = 540, -- Level Sync activated. Your level has been restricted to <number>. Equipment affected by the level restriction will be adjusted accordingly. Experience points will become unavailable for all party members should the Level Sync designee stray too far from the enemy.
	-- = 541, -- Level Sync could not be activated. The designated player is below level 10.
	-- = 542, -- Level Sync could not be activated. The designated player is in a different area.
	-- = 543, -- Level Sync could not be activated. One or more party members are currently under the effect of a status which prevents synchronization.
	-- = 544, -- Level synchronization will be removed in <number> seconds.
	-- = 545, -- No experience points gained...The Level Sync designee is either too far from the enemy, or unconscious.
	-- = 546, -- Your <status> effect duration has been extended.
	-- = 547, -- This ability can only be used on targets under the effect of a helix.
	-- = 548, -- The party member you have selected is incapable of receiving experience points, and as such cannot be a Level Sync designee.
	-- = 549, -- No experience points gained...The Level Sync designee is incapable of receiving experience points.
	-- = 550, -- Level Sync will be deactivated in <number> seconds. One or more party members have received the effect of a status which prevents synchronization.
	-- = 551, -- Level Sync will be deactivated in <number> seconds. The party leader or the Level Sync designee has left the area.
	-- = 552, -- Level Sync will be deactivated in <number> seconds. Less than two party members fulfill the requirements for Level Sync.
	-- = 553, -- Level Sync will be deactivated in <number> seconds. The party leader has removed synchronization, or the Level Sync designee has left the party.
	-- = 554, -- Level Sync will be deactivated in <number> seconds. The Level Sync designee has fallen below level 10.
	-- = 555, -- Level Sync will be deactivated in <number> seconds. A party member has undergone a job change.
	-- = 556, -- Level Sync will be deactivated in <number> seconds. The Level Sync designee is incapable of receiving experience points.
	-- = 557, -- <user> receives <number> pieces of alexandrite.
	-- = 560, -- <user> uses <ability>. Finishing move(s) now <number>.
	-- = 561, -- Unable to perform that action. Your have already earned the maximum number of finishing moves.
	-- = 563, -- <user> destroys <target>.
	-- = 564, -- <target> were destroyed.
	-- = 567, -- <user> stowed away an <item> in his/her tattered Maze Monger pouch.
	-- = 568, -- Your tattered Maze Monger pouch already contains an <item> and cannot hold another.
	STATUS_PREVENTS        = 569, -- Your current status prevents you from using that ability.
	-- = 570, -- <caster> casts <spell>. <number> of <target>'s status ailments disappears!
	-- = 571, -- <number> of <target>'s status ailments disappear!
	-- = 573, -- <target> or an alliance member is participating in a union. Ineligible to obtain treasure from this enemy.
	-- = 576, -- <attacker>'s ranged attack hits <defender> squarely for <number> point(s) of damage!
	-- = 577, -- <attacker>'s ranged attack strikes true, pummeling <defender> for <number> point(s) of damage!
	-- = 578, -- Hunt objective fulfilled! Please report to a hunt registry to collect your reward.
	-- = 579, -- Unable to use the <item>. Party leaders or those not in a party cannot use an <item>.
	-- = 580, -- Unable to use the <item>. The party leader is in either an area beyond warping range or a place you have yet to visit.
	-- = 582, -- <target> obtains <number> gil.
	-- = 583, -- Trial <number>: <number> objectives remain.
	-- = 585, -- <user> uses <ability>. <target>'s enmity towards <user> is <number>%.
	-- = 586, -- Towards <party member> is <number>%.
	-- = 587, -- <target> regains <number> HP.
	-- = 588, -- <target> regains <number> MP.
	-- = 589, -- <target> have been healed of <number> ailments.
	-- = 590, -- You can now perform <skill>.
	-- = 591, -- <user> uses <ability>. <target> is afflicted with Bewildered Daze (lv.<number>).
	-- = 592, -- <defender> attempts to counter <attacker>'s attack, but misses.
	
	-- = 600, -- <user> eats a <item>. The <user> finds a <item> inside!
	-- = 601, -- Objective fulfilled! Please report to a Dominion Sergeant to collect your reward.
	-- = 602, -- <user> uses <ability>. <target> receives the effect of <status>.
	TREASURE_HUNTER_UP     = 603, -- Additional effect: Treasure Hunter effectiveness against <target> increases to <number>.
	-- = 605, -- Additional effect: <target> falls to the ground.
	-- = 606, -- <defender> absorbs <attacker>'s counter. <defender> recovers <number> HP.
	-- = 607, -- <user> uses <skill>. <number> of <target>'s status ailments disappear!
	ABILITY_TH             = 608, -- <user> uses <ability>. Treasure Hunter effectiveness against <target> increases to <number>.
	-- = 609, -- Prowess attained: Increased treasure casket discovery.
	-- = 610, -- Prowess attained: Increased combat and magic skill gain.
	-- = 611, -- Prowess attained: Increased crystal yield.
	-- = 612, -- Prowess attained: Treasure Hunter bonus.
	-- = 613, -- Prowess attained: Increased attack speed.
	-- = 614, -- Prowess attained: Increased HP and MP.
	-- = 615, -- Prowess attained: Enhanced accuracy and ranged accuracy.
	-- = 616, -- Prowess attained: Enhanced attack and ranged attack.
	-- = 617, -- Prowess attained: Enhanced magic accuracy and magic attack.
	-- = 618, -- Prowess attained: Enhanced "Cure" potency.
	-- = 619, -- Prowess attained: Increased weapon skill damage.
	-- = 620, -- Prowess attained: "Killer" effects bonus.
	-- = 621, -- Blank line
	-- = 622, -- Blank line
	-- = 623, -- Blank line
	-- = 624, -- Blank line
	-- = 625, -- Prowess boosted: Increased treasure casket discovery.
	-- = 626, -- Prowess boosted: Increased combat and magic skill gain.
	-- = 627, -- Prowess boosted: Increased crystal yield.
	-- = 628, -- Prowess boosted: Treasure Hunter bonus.
	-- = 629, -- Prowess boosted: Increased attack speed.
	-- = 630, -- Prowess boosted: Increased HP and MP.
	-- = 631, -- Prowess boosted: Enhanced accuracy and ranged accuracy.
	-- = 632, -- Prowess boosted: Enhanced attack and ranged attack.
	-- = 633, -- Prowess boosted: Enhanced magic accuracy and magic attack.
	-- = 634, -- Prowess boosted: Enhanced "Cure" potency.
	-- = 635, -- Prowess boosted: Increased weapon skill damage.
	-- = 636, -- Prowess boosted: "Killer" effects bonus.
	-- = 637, -- Blank line
	-- = 638, -- Blank line
	-- = 639, -- Blank line
	-- = 640, -- Blank line
	-- = 641, -- Additional effect: <number> of <target>'s attributes are drained.
	-- = 642, -- <caster> casts <spell>. <caster> absorbs <number> of <target>'s status benefits.
	-- = 644, -- <user> uses <ability>. <number> of <target>'s status effects are removed.
	-- = 645, -- <user> uses <ability>. <target> is <status>.
	-- = 646, -- <user> uses <ability>. <target> falls to the ground.
	-- = 647, -- <caster> casts <spell>. <target>'s <status> effect disappears!
	-- = 648, -- <caster> leads the casting of <spell>. <target> takes <number> point(s) of damage.
	-- = 649, -- A member of another party is readying <spell> against your target. You cannot cast the same spell at this time.
	-- = 650, -- <caster> leads the casting of <spell>. Magic Burst! <target> takes <number> point(s) of damage.
	-- = 651, -- <caster> leads the casting of <spell>. <target> recovers <number> hit points.
	-- = 652, -- Additional effect: <target> loses <number> TP.
	-- = 653, -- <caster> casts <spell>. -><target> resists the spell. ->Immunobreak!
	-- = 654, -- -><target> resists the spell. ->Immunobreak!
	-- = 655, -- <caster> casts <spell>. -><target> completely resists the spell.
	-- = 656, -- -><target> completely resists the spell.
	-- = 657, -- <user> uses <ability>. ->All enmity is transferred to <target>.
	-- = 658, -- <user> uses <ability>, but misses <target>.
	-- = 659, -- No effect on <target>.
	-- = 660, -- The same effect is already active on that luopan!
	REQUIRES_RUNES = 666, -- This action requires the ability Rune Enchantment.
	SWORDPLAY = 667, -- <user> uses <ability>. Accuracy and evasion are enhanced.
	VALLATION = 668, -- <user> uses <ability>. <target> receives the effect of Vallation, reducing damage taken from certain elemental magic spells.
	VALIANCE = 669, -- Magic damage of a certain element is reduced for <target>.
	LIEMENT = 670, -- <user> uses <ability>. <target> can now absorb magic damage of a certain element.
	PFLUG = 671, -- <user> uses <ability>. <target> now has enhanced resistance.
	GAMBIT = 672, -- <user> uses <ability>. <target> receives the effect of Gambit, reducing defense against magic of a certain element.
	-- = 673, -- <target> obtains <number> corpuscles of mweya plasm.
	-- = 674, -- <user> uses <ability>, and finds <number> <item>.
	-- = 675, -- <user> readies <skill>.
	-- = 676, -- <user>'s movement speed increases.
	-- = 677, -- You are now able to possess a new monster!
	-- = 678, -- You have learned a new instinct!
	-- = 679, -- <monster> will return to the Feretory in: <number>.
	-- = 680, -- A newfound puissance courses through your veins.
	-- = 681, -- Your muscles ripple with an immensely powerful and invigorating force.
	-- = 682, -- Your puissance withers slightly.
	-- = 683, -- You have claimed <target>!
	-- = 684, -- <target> has been claimed!
	-- = 685, -- The enemy you are battling will no longer be claimed in: <number>.
	-- = 686, -- The enemy you were battling is no longer claimed.
	-- = 687, -- <user> captured <target>.
	-- = 688, -- <target> has fled!	
	-- = 689, -- <user> captured <target>.
	
	-- = 701, -- There's no time to do that now!
	-- = 702, -- Blank line
	-- = 703, -- Blank line
	-- = 704, -- You have undertaken "<RoE challenge number>".
	-- = 705, -- You have undertaken the limited-time Records of Eminence challenge "<RoE challenge number>".
	-- = 708, -- This place is now known as a location that brings memories flooding back to the <actor>.
	-- = 711, -- (Adventuring Fellow?) (<name>) It's far too late for your foes to make amends, and with me at your side, they'll meet untimely ends!
	-- = 712, -- (/checkparam) Primary Accuracy: <number> / Primary Attack: <number>.
	-- = 713, -- (/checkparam) Auxiliary Accuracy: <number> / Auxiliary Attack: <number>.
	-- = 714, -- (/checkparam) Ranged Accuracy: <number> / Ranged Attack: <number>.
	-- = 715, -- (/checkparam) Evasion: <number> / Defense: <number>.
	-- = 716, -- <caster> starts casting <spell>.
	-- = 718, -- <target> gains <number> capacity point(s). <target> earns a job point! (Total: <number>)
	-- = 720, -- CRASHES THE CLIENT
	-- = 721, -- You receive a bonus of <number> fishing guild point(s)!
	-- = 722, -- You receive a bonus of <number> woodworking guild point(s)!
	-- = 723, -- You receive a bonus of <number> smithing guild point(s)!
	-- = 724, -- You receive a bonus of <number> goldsmithing guild point(s)!
	-- = 725, -- You receive a bonus of <number> clothcraft guild point(s)!
	-- = 726, -- You receive a bonus of <number> leathercraft guild point(s)!
	-- = 727, -- You receive a bonus of <number> bonecraft guild point(s)!
	-- = 728, -- You receive a bonus of <number> alchemy guild point(s)!
	-- = 729, -- You receive a bonus of <number> cooking guild point(s)!
	-- = 730, -- <user> uses <skill>. <target>'s TP is reduced to <number>.
	-- = 731, -- (/checkparam) Average item level: <number>.
	-- = 732, -- Skillchain: Universal Enlightenment. <target> takes <number> point(s) of damage.
	-- = 733, -- <actor>:
	-- = 734, -- <user> uses <skill> on <target>.
	-- = 735, -- Capacity chain #<number>! <target> gains <number> capacity point(s).
	-- = 736, -- <user> uses <skill>. <number> HP drained from <target>.
	-- = 737, -- <user> uses <skill>. <number> of <target>'s magic effects is drained.
	-- = 738, -- <user> uses <skill>.
	MULTIPLE_ENFEEBLE = 739, -- <target> receives <number> magical effect(s).
	-- = 741, -- You receive <number> Unity accolade(s) for a total of <number>!
	-- = 742, -- You are currently unable to undertake this objective.
	-- = 743, -- <user> uses <skill>. <target>'s enmity decreases.
	-- = 745, -- Your automaton exceeds one or more elemental capacity values and cannot be activated.
	-- = 746, -- <user> uses <skill>. <number> TP drained from <target>.
	-- = 747, -- <user> uses <skill>. Magic Burst! <target> takes <number> point(s) of damage.
	-- = 748, -- <user> uses <skill>. Magic Burst! <number> HP drained from <target>.
	-- = 749, -- Magic Burst! <number> HP drained from <target>.
	-- = 750, -- <user> uses <skill>. Magic Burst! <number> MP drained from <target>.
	-- = 751, -- Magic Burst! <number> MP drained from <target>.
	-- = 752, -- <user> uses <skill>. Magic Burst! <number> TP drained from <target>.
	-- = 753, -- Magic Burst! <number> TP drained from <target>.
	-- = 754, -- <user> uses <skill>. Magic Burst! <target> is <status>.
	-- = 755, -- <user> uses <skill>. Magic Burst! <target> receives the effect of <status>.
	-- = 756, -- <defender>'s spikes cause <attacker> to fall to the ground.
	-- = 757, -- <number> of <target>'s effects disappears.
	OBTAINED_KEY_ITEM      = 758, -- Obtained key item: <key item>.
    ALREADY_HAVE_KEY_ITEM  = 759, -- You already have key item: <key item>.
	-- = 760, -- You are only able to possess one <item> and thus are unable to receive your just reward. Clear out your inventory and receive the item from the Records of Eminence Menu.
	-- = 761, -- You were unable to receive your just reward because you need 1 free space in your inventory. Clear out your bags and receive your item from the Records of Eminence Menu.
	-- = 762, -- <user> uses <skill>. All of <target>'s status parameters are boosted.
	-- = 763, -- <user> uses <skill>. <target> has grown noticeably bored.
	-- = 764, -- <user> uses <skill>. <target> feels the Fever!
	-- = 765, -- <user> uses a <item>. <target> obtains 2 escha silt.
	-- = 766, -- <user> uses a <item>. <target> obtains 2 escha beads.
	-- = 767, -- Skillchain: Radiance. <target> takes <number> points of damage.
	-- = 768, -- Skillchain: Umbra. <target> takes <number> points of damage.
	-- = 769, -- Skillchain: Radiance. <target> recovers <number> hit points!
	-- = 770, -- Skillchain: Umbra. <target> recovers <number> hit points!
	-- = 771, -- Congratulations! Your deeds of valor will ring throughout the ages, providing inspiration for generations to come.
	-- = 772, -- <player> stands resolute thanks to the power of the bonds that tie you!
	-- = 773, -- You are unable to call forth your mount because your main job level is not at least <number>.
	-- = 774, -- You already possess that item and are unable to receive your just reward!
	-- = 775, -- A new objective has been added in the Contents > Content (Ambuscade) Records or Eminence category!
	-- = 776, -- Additional Effect: <target> is chainbound.
	-- = 777, -- You cannot mount at this time.
	-- = 778, -- <user> uses <skill>. <user> copies <number> magical effect(s) from <target>.
	-- = 779, -- <user> uses <skill>. A barrier begins to pulsate around <target>.
	-- = 780, -- <user> uses <skill>. <user> takes aim at <target>!
	-- = 781, -- <defender> retaliates, absorbing <number> TP from <attacker>.
	-- = 782, -- The bonus conditions for increasing the Craftsmanship has changed to {FIR}%+d !
	-- = 783, -- The Craftsmanship bonus conditions have disappeared!
	-- = 784, -- Craftsmanship has increased by <number>.<number>%! (ex. 1.1%)
	-- = 785, -- Craftsmanship has increased by <number>.0<number>%! (ex. 1.01%)
	-- = 786, -- Craftsmanship has increased to <number>%! (ex. 1%)
	-- = 787, -- <player> has had the fun sucked out of them!
	-- = 788, -- <player> no longer recalls what fun is...
	-- = 790, -- The <item> contains <number> gil.
	-- = 791, -- <target> uses <skill>. <target> receives <number> motes of paradise.
	-- = 792, -- <target> uses <spell>. <number> of <target>'s effects disappear!
	-- = 793, -- you find <number> <item>.
	-- = 794, -- You find <number> <item>. (plural)
	-- = 795, -- You receive <number> deeds of heroism, for a total of <number>!
	-- = 796, -- <player> gains potpourri for a total of <number>!
	-- = 797, -- <player> attains level <number>!
	OVERLOAD_CHANCE = 798, -- <user>'s <PUP maneuver> overload chance is <number>%.
	OVERLOAD_CHANCE_OVERLOADED = 799, -- <user>'s <PUP maneuver> overload chance is <number>%. <user> is overloaded!
	
	-- STATUS_ACTIVATES = 800, -- <status> activates. <target> takes <number> point(s) of damage.
	-- STATUS_EXPIRE_USE_ITEM = 801, -- You cannot use the <item> until the <status> effect expires.
	-- = 802, -- The <user> uses <skill>. <number> HP drained from <target>.
	-- = 803, -- <user> uses <spell>. Magic Burst! <number> HP drained from <target>.
	-- = 804, -- <user> uses <spell. Magic Burst! <target> receives the effect of <status>.
	-- = 805, -- <user> uses <skill>. <target>'s <status> effect disappears!
	-- = 806, -- <target>'s <status> effect disappears!
	-- = 807, -- <target> receives <number> job points.

    -- Distance
    TARG_OUT_OF_RANGE      = 4,   -- <target> is out of range.
    UNABLE_TO_SEE_TARG     = 5,   -- Unable to see <target>.
    LOSE_SIGHT             = 36,  -- You lose sight of <target>.
    TOO_FAR_AWAY           = 78,  -- <target> is too far away.

    -- Weaponskills
    READIES_WS             = 43,  -- ${actor} readies ${weapon_skill}.
    CANNOT_USE_WS          = 190, -- The <player> cannot use that weapon ability.
    NOT_ENOUGH_TP          = 192, -- The <player> does not have enough TP.

    -- Pets
    REQUIRES_A_PET         = 215, -- That action requires a pet.
    THAT_SOMEONES_PET      = 235, -- That is someone's pet.
    ALREADY_HAS_A_PET      = 315, -- The <player> already has a pet.
    NO_EFFECT_ON_PET       = 336, -- No effect on that pet.
    NO_JUG_PET_ITEM        = 337, -- You do not have the necessary item equipped to call a beast.
    MUST_HAVE_FOOD         = 347, -- You must have pet food equipped to use that command.
    STATUS_INCREASED       = 562, -- The status parameters of ${target} have increased.
    PET_CANNOT_DO_ACTION   = 574, -- <player>'s pet is currently unable to perform that action.
    PET_NOT_ENOUGH_TP      = 575, -- <player>'s pet does not have enough TP to perform that action.

    -- Food
    IS_FULL                 = 246,  -- ${target} is full.
    CANNOT_EAT              = 247,  -- ${actor} can't eat the ${item}.
    EATS_FINDS_ITEM         = 600,  -- ${actor} eats a ${item}.${lb}${actor} finds a ${item2} inside!
    EATS_FINDS_NOTHING      = 604,  -- ${actor} eats a ${item}, but finds nothing inside...

    -- Items
    ITEM_USES               = 28,   -- ${actor} uses a ${item}.
    ITEM_UNABLE_TO_USE      = 55,   -- Unable to use item.
    ITEM_UNABLE_TO_USE_2    = 56,   -- Unable to use item.
    ITEM_FAILS_TO_ACTIVATE  = 62,   -- The ${item} fails to activate.
    ITEM_NO_PETRAS          = 65,   -- You are not carrying any Petras.${lb}You cannot use the ${item}.
    ITEM_DOES_NOT_HAVE      = 91,   -- ${actor} does not have any ${item}.
    ITEM_CANNOT_USE_ON      = 92,   -- Cannot use the ${item} on ${target}.
    ITEM_YOU_OBTAIN_FROM    = 98,   -- You obtain a ${item} from ${target}.
    ITEM_NO_USE_LEVEL       = 104,  -- Unable to use item.${lb}You do not meet the level requirement.
    ITEM_NO_USE_MEDICATED   = 111,  -- You cannot use ${item} while medicated.
    ITEM_NO_USE_INVENTORY   = 308,  -- Unable to use the ${item}.${lb}${target}'s inventory is full.
    ITEM_RECEIVES_EFFECT    = 375,  -- ${actor} uses a ${item}.${lb}${target} receives the effect of ${status}.
    ITEM_OBTAINS_A          = 376,  -- ${actor} uses a ${item}.${lb}${target} obtains a ${item2}.
    ITEM_OBTAINS            = 377,  -- ${actor} uses a ${item}.${lb}${target} obtains ${item2}.
    ITEM_EFFECT_DISAPPEARS  = 378,  -- ${actor} uses a ${item}.${lb}${target}'s ${status} effect disappears!

    -- Ranged
    NO_RANGED_WEAPON       = 216, -- You do not have an appropriate ranged weapon equipped.
    CANNOT_SEE             = 217, -- You cannot see <target>.
    MOVE_AND_INTERRUPT     = 218, -- You move and interrupt your aim.

    -- Additional effects and spike effects
    SPIKES_EFFECT_DMG      = 44 , -- <Defender>'s spikes deal <number> points of damage to the <Attacker>.
    SPIKES_EFFECT_HP_DRAIN = 132, -- <Defender>'s spikes drain <number> HP from the <Attacker>.
    ADD_EFFECT_MP_HEAL     = 152, -- Additional effect: The <player> recovers <number> MP.
    ADD_EFFECT_STATUS      = 160, -- Additional effect: <Status Effect>.
    ADD_EFFECT_HP_DRAIN    = 161, -- Additional effect: <number> HP drained from <target>.
    ADD_EFFECT_MP_DRAIN    = 162, -- Additional effect: <number> MP drained from <target>.
    ADD_EFFECT_DMG         = 163, -- Additional effect: <number> points of damage.
    ADD_EFFECT_STATUS_2    = 164, -- Additional effect: <Status Effect>. (Duplicate?)
    ADD_EFFECT_TP_DRAIN    = 165, -- Additional effect: <number> TP drained from <target>.
    ADD_EFFECT_STATUS_3    = 166, -- Additional effect: The <target> gains the effect of <Status Effect>. (Only difference from 160 and 164 is "The")
    ADD_EFFECT_HP_HEAL     = 167, -- Additional effect: The <player> recovers <number> HP.
    ADD_EFFECT_DISPEL      = 168, -- Additional effect: <target>'s <Status Effect> effect disappears!
    ADD_EFFECT_WARP        = 169, -- Additional effect: Warp! (used by Halloween staves)
    STATUS_SPIKES          = 374, -- Striking <defender>'s armor causes <attacker> to become <status effect>.
    SPIKES_EFFECT_HEAL     = 383, -- <?>'s spikes restore <number> HP to the <?>.
    ADD_EFFECT_HEAL        = 384, -- Additional effect: <target> recovers <number> HP.

    -- Status
    RECOVERS_HP             = 24,   -- ${target} recovers ${number} HP.
    RECOVERS_MP             = 25,   -- ${target} recovers ${number} MP.
    RECOVERS_HP_AND_MP      = 26,   -- ${target} recovers ${number} HP and MP.
    IS_STATUS               = 203,  -- ${target} is ${status}.
    IS_NO_LONGER_STATUS     = 204,  -- ${target} is no longer ${status}.
    GAINS_EFFECT_OF_STATUS  = 205,  -- ${target} gains the effect of ${status}.
    STATUS_WEARS_OFF        = 206,  -- ${target}'s ${status} effect wears off.
    ABOUT_TO_WEAR_OFF       = 251,  -- The effect of ${status} is about to wear off.
    ALL_ABILITIES_RECHARGED = 361,  -- All of ${target}'s abilities are recharged.

    -- Battlefield
    UNABLE_TO_ACCESS_SJ     = 107, -- <player> is temporarily unable to access support job abilities
    TIME_LEFT               = 202,  -- Time left: (0:00:00)

    -- Dynamis
    TIME_DYNAMIS_EXTENDED  = 448, -- Time allowed in Dynamis has been extended by <param> minutes
    TIME_DYNAMIS_REMAINING = 449, -- ----== WARNING ==----Time remaining in Dynamis: <param> minutes.
    -- Charm
    CANNOT_CHARM           = 210, -- <actor> cannot charm <target>!
    VERY_DIFFICULT_CHARM   = 211, -- It would be very difficult for <actor> to charm <target>.
    DIFFICULT_TO_CHARM     = 212, -- It would be difficult for <actor> to charm <target>.
    MIGHT_BE_ABLE_CHARM    = 213, -- <actor> might be able to charm <target>.
    SHOULD_BE_ABLE_CHARM   = 214, -- <actor> should be able to charm <target>.

    -- BLU
    LEARNS_SPELL           = 419, -- <target> learns <spell>!

    -- COR
    ROLL_MAIN              = 420, -- The <player> uses .. The total comes to ..! <target> receives the effect of ..
    ROLL_SUB               = 421, -- <target> receives the effect of ..
    ROLL_MAIN_FAIL         = 422, -- The <player> uses .. The total comes to ..! No effect on <target>.
    ROLL_SUB_FAIL          = 423, -- No effect on <target>.
    DOUBLEUP               = 424, -- The <player> uses Double-Up. The total for . increases to ..! <target> receives the effect of ..
    DOUBLEUP_FAIL          = 425, -- The <player> uses Double-Up. The total for . increases to ..! No effect on <target>.
    DOUBLEUP_BUST          = 426, -- The <player> uses Double-Up. Bust! <target> loses the effect of ..
    DOUBLEUP_BUST_SUB      = 427, -- <target> loses the effect of ..
    NO_ELIGIBLE_ROLL       = 428, -- There are no rolls eligible for Double-Up. Unable to use ability.
    ROLL_ALREADY_ACTIVE    = 429, -- The same roll is already active on the <player>.

    EFFECT_ALREADY_ACTIVE  = 523, -- The same effect is already active on <player>.

    -- PLD
    COVER_SUCCESS          = 311, -- The <player> covers <target>.
    COVER_FAILURE          = 312, -- The <player>'s attempt to cover has no effect.

    -- DNC
    NO_FINISHINGMOVES      = 524, -- You have not earned enough finishing moves to perform that action.
    SPECTRAL_JIG           = 532, -- <user> uses <ability>. <target> receives the effect of Sneak and Invisible.

    -- GEO
    SAME_EFFECT_LUOPAN     = 660, -- The same effect is already active on that luopan!.
    LUOPAN_ALREADY_PLACED  = 661, -- <player> has already placed a luopan. Unable to use ability.
    REQUIRE_LUOPAN         = 662, -- This action requires a luopan.
    LUOPAN_HP_RATE_DOWN    = 663, -- <player> uses <ability>. The luopan's HP consumption rate has been reduced.
    LUOPAN_HP_RATE_UP      = 664, -- <player> uses <ability>. The luopan's HP consumption rate has been increased.
    HAS_LUOPON_NO_USE      = 665, -- <player> has a pet. Unable to use ability.

    -- Fields / Grounds of Valor
    FOV_DEFEATED_TARGET     = 558,  -- You defeated a designated target.${lb}(Progress: ${number}/${number2})
    FOV_COMPLETED_REGIME    = 559,  -- You have successfully completed the training regime.
    FOV_OBTAINS_GIL         = 565,  -- ${target} obtains ${gil}.
    FOV_OBTAINS_TABS        = 566,  -- ${target} obtains ${number} tab.${lb}(Total: ${number})
    FOV_REGIME_BEGINS_ANEW  = 643,  -- Your current training regime will begin anew!

    -- Magian Trials
    MAGIAN_TRIAL_COMPLETE   = 584,  -- You have completed Trial <trialID>. Report your success to a Magian Moogle.

    -- Depoil Statuses
    DESPOIL_ATT_DOWN        = 593,  -- ${actor} uses ${ability}.${lb}${actor} steals a ${item} from ${target}.${lb}Additional effect: ${target} is afflicted with Attack Down.
    DESPOIL_DEF_DOWN        = 594,  -- ${actor} uses ${ability}.${lb}${actor} steals a ${item} from ${target}.${lb}Additional effect: ${target} is afflicted with Defense Down.
    DESPOIL_MATT_DOWN       = 595,  -- ${actor} uses ${ability}.${lb}${actor} steals a ${item} from ${target}.${lb}Additional effect: ${target} is afflicted with Magic Atk. Down.
    DESPOIL_MDEF_DOWN       = 596,  -- ${actor} uses ${ability}.${lb}${actor} steals a ${item} from ${target}.${lb}Additional effect: ${target} is afflicted with Magic Def. Down.
    DESPOIL_EVA_DOWN        = 597,  -- ${actor} uses ${ability}.${lb}${actor} steals a ${item} from ${target}.${lb}Additional effect: ${target} is afflicted with Evasion Down.
    DESPOIL_ACC_DOWN        = 598,  -- ${actor} uses ${ability}.${lb}${actor} steals a ${item} from ${target}.${lb}Additional effect: ${target} is afflicted with Accuracy Down.
    DESPOIL_SLOW            = 599,  -- ${actor} uses ${ability}.${lb}${actor} steals a ${item} from ${target}.${lb}Additional effect: ${target} is afflicted with Slow.

    -- Records of Eminence
    ROE_COMPLETE            = 690,  -- You have completed the following Records of Eminence objective: <record>.
    ROE_REPEAT_OR_CANCEL    = 691,  -- This objective may be repeated, and can be cancelled from the menu.
    ROE_RECEIVE_SPARKS      = 692,  -- You receive <amount> sparks of eminence, and now possess a total of <amount>.
    ROE_BONUS_ITEM          = 693,  -- As a special bonus for your valiant efforts, you have been awarded <item>!
    ROE_BONUS_SPARKS        = 694,  -- As a special bonus for your valiant efforts, you have been awarded <amount> sparks of eminence!
    ROE_UNABLE_BONUS_ITEM   = 695,  -- Unable to receive special bonus. Make room in your inventory and receive your reward from the Records of Eminence menu.
    ROE_YET_TO_RECEIVE      = 696,  -- You have yet to receive certain special bonuses from the objectives you have completed. Make room in your inventory and receive your reward from the Records of Eminence menu.
    ROE_RECORD              = 697,  -- Records of Eminence: <record>.
    ROE_PROGRESS            = 698,  -- Progress: <amount>/<amount>.
    ROE_NEW_OBJECTIVE       = 699,  -- A new objective has been added!
    ROE_OBTAINED_KEY_ITEM   = 706,  -- You have obtained <key item> as a special reward!
    ROE_FIRST_TIME_SPARKS   = 707,  -- As a first-time bonus, you receive <amount> sparks of eminence for a total of <amount>!
    ROE_BONUS_ITEM_PLURAL   = 709,  -- As a special bonus for your valiant efforts, you have been awarded the following: <itemid> x<amount>!
    ROE_TIMED_CLEAR         = 710,  -- You are cleared to fulfill this objective once again.

    -- TRUST & ALTER EGO
    TRUST_NO_CAST_TRUST     = 700,  -- You are unable to use Trust magic at this time.
    TRUST_NO_CALL_AE        = 717,  -- You cannot call forth alter egos here.
}

------------------------------------
-- System Messages
------------------------------------

tpz.msg.system =
{
    GLOBAL_TRUST_OFFSET          = 0,
    TRUST_NO_SEEKING_PARTY       = 296, -- You cannot use Trust magic while seeking a party.
    TRUST_DELAY_NEW_PARTY_MEMBER = 297, -- While inviting a party member, you must wait a while before using Trust magic.
    TRUST_MAXIMUM_NUMBER         = 298, -- You have called forth your maximum number of alter egos.
    TRUST_ALREADY_CALLED         = 299, -- That alter ego has already been called forth.
    TRUST_NO_ENMITY              = 300, -- You cannot use Trust magic while having gained enmity.
    TRUST_SOLO_OR_LEADER         = 301, -- You cannot use Trust magic unless you are solo or the party leader.
}
