---------------------------------------------------------------------------------------------------
-- func: !killcount <page number>
-- desc: Gets the player's Character Variables that have stored their kill counts
---------------------------------------------------------------------------------------------------

cmdprops =
{
    permission = 0,
    parameters = "i"
}

function onTrigger(player, page)
	-- Sky
	local kcUllikummi = player:getCharVar("KillCounter_Ullikummi")
	local kcDespot = player:getCharVar("KillCounter_Despot")
	local kcOlla = player:getCharVar("KillCounter_Olla")
	local kcZipacna = player:getCharVar("KillCounter_Zipacna")
	local kcMotherGlobe = player:getCharVar("KillCounter_MotherGlobe")
	local kcSteamCleaner = player:getCharVar("KillCounter_SteamCleaner")
	local kcFaust = player:getCharVar("KillCounter_Faust")
	local kcBrigBlade = player:getCharVar("KillCounter_BrigandishBlade")
	local kcByakko = player:getCharVar("KillCounter_Byakko")
	local kcGenbu = player:getCharVar("KillCounter_Genbu")
	local kcSeiryu = player:getCharVar("KillCounter_Seiryu")
	local kcSuzaku = player:getCharVar("KillCounter_Suzaku")
	local kcKirin = player:getCharVar("KillCounter_Kirin")
	-- Sea
	local kcIxAernMNK = player:getCharVar("KillCounter_IxAernMNK")
	local kcIxAernDRK = player:getCharVar("KillCounter_IxAernDRK")
	local kcIxAernDRG = player:getCharVar("KillCounter_IxAernDRG")
	local kcJailOfTemp = player:getCharVar("KillCounter_JailOfTemp")
	local kcJailOfFort = player:getCharVar("KillCounter_JailOfFort")
	local kcJailOfFaith = player:getCharVar("KillCounter_JailOfFaith")
	local kcJailOfHope = player:getCharVar("KillCounter_JailOfHope")
	local kcJailOfJust = player:getCharVar("KillCounter_JailOfJust")
	local kcJailOfPrud = player:getCharVar("KillCounter_JailOfPrud")
	local kcJailOfLove = player:getCharVar("KillCounter_JailOfLove")
	local kcAbsoluteVirtue = player:getCharVar("KillCounter_AbsoluteVirtue")
	-- Abyssea
	local kcRabbit = player:getCharVar("KillCounter_Rabbits")
	local kcMarvin = player:getCharVar("KillCounter_MangyTailedMarvin")
	-- Battlefields
	local kcSL = player:getCharVar("KillCounter_ShadowLord")
	local kcKammy = player:getCharVar("KillCounter_Kamlanaut")
	local kcDivineMight = player:getCharVar("KillCounter_DivineMight")
	local kcAAEV = player:getCharVar("KillCounter_AAEV")
	local kcAAGK = player:getCharVar("KillCounter_AAGK")
	local kcAAHM = player:getCharVar("KillCounter_AAHM")
	local kcAAMR = player:getCharVar("KillCounter_AAMT")
	local kcAATT = player:getCharVar("KillCounter_AATT")
	-- Voidwatch
	local kcCelaeno = player:getCharVar("KillCounter_Celaeno")
	local kcHahava = player:getCharVar("KillCounter_Hahava")
	local kcVoidwrought = player:getCharVar("KillCounter_Voidwrought")
	local kcCherufe = player:getCharVar("KillCounter_Cherufe")
	local kcTaweret = player:getCharVar("KillCounter_Taweret")
	local kcYatagarasu = player:getCharVar("KillCounter_Yatagarasu")
	local kcAgathos = player:getCharVar("KillCounter_Agathos")
	local kcGoji = player:getCharVar("KillCounter_Goji")
	local kcGugalanna = player:getCharVar("KillCounter_Gugalanna")
	local kcAkvan = player:getCharVar("KillCounter_Akvan")
	local kcKaggen = player:getCharVar("KillCounter_Kaggen")
	local kcPil = player:getCharVar("KillCounter_Pil")
	-- HNM
	local kcAdamantoise = player:getCharVar("KillCounter_Adamantoise")
	local kcBehemoth = player:getCharVar("KillCounter_Behemoth")
	local kcFafnir = player:getCharVar("KillCounter_Fafnir")
	local kcAspidochelone = player:getCharVar("KillCounter_Aspidochelone")
	local kcKingBehemoth = player:getCharVar("KillCounter_King_Behemoth")
	local kcNidhogg = player:getCharVar("KillCounter_Nidhogg")
	local kcTiamat = player:getCharVar("KillCounter_Tiamat")
	local kcJormungand = player:getCharVar("KillCounter_Jormungand")
	local kcVrtra = player:getCharVar("KillCounter_Vrtra")
	local kcBres = player:getCharVar("KillCounter_Bres")
	local kcRugaroo = player:getCharVar("KillCounter_Rugaroo")
	local kcVeeLadu = player:getCharVar("KillCounter_Vee_Ladu_the_Titte")
	-- Abyssea NM
	local kcBriareus = player:getCharVar("KillCounter_Briareus")
	local kcGlavoid = player:getCharVar("KillCounter_Glavoid")
	local kcKukulkan = player:getCharVar("KillCounter_Kukulkan")
	local kcCireinCroin = player:getCharVar("KillCounter_CireinCroin")
	local kcItzpapalotl = player:getCharVar("KillCounter_Itzpapalotl")
	local kcSedna = player:getCharVar("KillCounter_Sedna")
	local kcAmphitrite = player:getCharVar("KillCounter_Amphitrite")
	local kcBennu = player:getCharVar("KillCounter_Bennu")
	local kcResheph = player:getCharVar("KillCounter_Resheph")
	-- Arbitrary NM
	local kcRomwe = player:getCharVar("KillCounter_Baronet_Romwe")
	local kcVapula = player:getCharVar("KillCounter_Baron_Vapula")
	local kcBifrons = player:getCharVar("KillCounter_Count_Bifrons")
	local kcMorax = player:getCharVar("KillCounter_Viscount_Morax")
	local kcHaborym = player:getCharVar("KillCounter_Duke_Haborym")
	local kcBatym = player:getCharVar("KillCounter_Grand_Duke_Batym")
	local kcAllocen = player:getCharVar("KillCounter_Marquis_Allocen")
	local kcAmon = player:getCharVar("KillCounter_Marquis_Amon")
	local kcAndrealphus = player:getCharVar("KillCounter_Marquis_Andrealphu")
	local kcNaberius = player:getCharVar("KillCounter_Marquis_Naberius")
	local kcMooOuzi = player:getCharVar("KillCounter_Moo_Ouzi_the_Swift")
	local kcMeeDeggi = player:getCharVar("KillCounter_Mee_Deggi_the_Puni")
	local kcQuuDomi = player:getCharVar("KillCounter_Quu_Domi_the_Galla")
	local kcYaaHaqa = player:getCharVar("KillCounter_Yaa_Haqa_the_Profa")
	local kcBlubberyBulge = player:getCharVar("KillCounter_Blubbery_Bulge")
	local kcGochakzuk = player:getCharVar("KillCounter_Dirtyhanded_Gochak")
	local kcDnatbat = player:getCharVar("KillCounter_Hawkeyed_Dnatbat")
	local kcGnadgad = player:getCharVar("KillCounter_Poisonhand_Gnadgad")
	local kcGudrud = player:getCharVar("KillCounter_Steelbiter_Gudrud")
	local kcBakdak = player:getCharVar("KillCounter_Tigerbane_Bakdak")
	local kcBiGho = player:getCharVar("KillCounter_BiGho_Headtaker")
	local kcGaBhu = player:getCharVar("KillCounter_GaBhu_Unvanquished")
	local kcDaDha = player:getCharVar("KillCounter_DaDha_Hundredmask")
	local kcGeDha = player:getCharVar("KillCounter_GeDha_Evileye")
	local kcZoKho = player:getCharVar("KillCounter_ZoKhu_Blackcloud")
	local kcPallas = player:getCharVar("KillCounter_Pallas")
	local kcAlkyoneus = player:getCharVar("KillCounter_Alkyoneus")
	local kcIxtab = player:getCharVar("KillCounter_Ixtab")
	local kcHakutaku = player:getCharVar("KillCounter_Hakutaku")
	local kcFriarRush = player:getCharVar("KillCounter_Friar_Rush")
	local kcBilberry = player:getCharVar("KillCounter_Sozu_Bilberry")
	local kcPontifex = player:getCharVar("KillCounter_Tonberry_Pontifex")
	local kcOgama = player:getCharVar("KillCounter_Ogama")
	
	if (page == nil) then
		player:PrintToPlayer(string.format("Please specify page 1 or 2 (e.g. !killcount 1 or !killcount 2)"),tpz.msg.channel.SYSTEM_3)
	elseif (page == 1) then
		player:PrintToPlayer(string.format("SKY ------------------------------------------------------------------------------------------------------------------------------------------------"),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Ullikummi: [%i]  Despot: [%i]  Olla: [%i]  Zipacna: [%i]  Mother Globe: [%i]  Steam Cleaner: [%i]  Faust: [%i]  Brigandish Blade: [%i]", kcUllikummi, kcDespot, kcOlla, kcZipacna, kcMotherGlobe, kcSteamCleaner, kcFaust, kcBrigBlade),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Byakko: [%i]  Genbu: [%i]  Seiryu: [%i]  Suzaku: [%i]  Kirin: [%i]", kcByakko, kcGenbu, kcSeiryu, kcSuzaku, kcKirin),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("SEA ------------------------------------------------------------------------------------------------------------------------------------------------"),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Ix'Aern (MNK): [%i]  Ix'Aern (DRK): [%i]  Ix'Aern (DRG): [%i]  Jailer of Temperance: [%i]  Jailer of Fortitude: [%i]  Jailer of Faith: [%i]", kcIxAernMNK, kcIxAernDRK, kcIxAernDRG, kcJailOfTemp, kcJailOfFort, kcJailOfFaith),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Jailer of Hope: [%i]  Jailer of Justice: [%i]  Jailer of Prudence: [%i]  Jailer of Love: [%i]  Absolute Virtue: [%i]", kcJailOfHope, kcJailOfJust, kcJailOfPrud, kcJailOfLove, kcAbsoluteVirtue),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("BATTLEFIELDS ---------------------------------------------------------------------------------------------------------------------------------------"),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Shadow Lord: [%i]  Kam'lanaut: [%i]  Divine Might: [%i]", kcSL, kcKammy, kcDivineMight),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  AAEV: [%i]  AAGK: [%i]  AAHM: [%i]  AAMR: [%i]  AATT: [%i]", kcAAEV, kcAAGK, kcAAHM, kcAAMR, kcAATT),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("VOIDWATCH ------------------------------------------------------------------------------------------------------------------------------------------"),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  City - Celaeno: [%i]  Hahava: [%i]  Voidwrought: [%i]", kcCelaeno, kcHahava, kcVoidwrought),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Jeuno - Cherufe: [%i]  Taweret: [%i]  Yatagarasu: [%i]  Agathos: [%i]  Goji: [%i]  Gugalanna: [%i]", kcCherufe, kcTaweret, kcYatagarasu, kcAgathos, kcGoji, kcGugalanna),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Sinister Reign - Akvan: [%i]  Kaggen: [%i]  Pil: [%i]", kcAkvan, kcKaggen, kcPil),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("HNM ------------------------------------------------------------------------------------------------------------------------------------------------"),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Land Princes - Adamantoise: [%i]  Behemoth: [%i]  Fafnir: [%i]", kcAdamantoise, kcBehemoth, kcFafnir),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Land Kings - Aspidochelone: [%i]  King Behemoth: [%i]  Nidhogg: [%i]", kcAspidochelone, kcKingBehemoth, kcNidhogg),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Wyrms - Tiamat: [%i]  Jormungand: [%i]  Vrtra: [%i]", kcTiamat, kcJormungand, kcVrtra),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Volte - Bres: [%i]  Rugaroo: [%i]  Vee Ladu: [%i]", kcBres, kcRugaroo, kcVeeLadu),tpz.msg.channel.SYSTEM_3)
	elseif (page == 2) then
		player:PrintToPlayer(string.format("ABYSSEA NM -----------------------------------------------------------------------------------------------------------------------------------------"),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Briareus: [%i]  Glavoid: [%i]  Kukulkan: [%i]", kcBriareus, kcGlavoid, kcKukulkan),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("ARBITRARY NM ---------------------------------------------------------------------------------------------------------------------------------------"),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Baronet Romwe: [%i]  Baron Vapula: [%i]  Count Bifrons: [%i]  Viscount Morax: [%i]  Duke Haborym: [%i]  Grand Duke Batym: [%i]  Marquis Allocen: [%i]", kcRomwe, kcVapula, kcBifrons, kcMorax, kcHaborym, kcBatym, kcAllocen),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Marquis Amon: [%i]  Marquis Andrealphus: [%i]  Marquis Naberius: [%i]  Moo Ouzi: [%i]  Mee Deggi: [%i]  Quu Domi: [%i]  Yaa Haqa: [%i]", kcAmon, kcAndrealphus, kcNaberius, kcMooOuzi, kcMeeDeggi, kcQuuDomi, kcYaaHaqa),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Blubbery Bulge: [%i]  Gochakzuk: [%i]  Dnatbat: [%i]  Gnadgad: [%i]  Gudrud: [%i]  Bakdak: [%i]  Bi'Gho: [%i]  Ga'Bhu: [%i]  Da'Dha: [%i]", kcBlubberyBulge, kcGochakzuk, kcDnatbat, kcGnadgad, kcGudrud, kcBakdak, kcBiGho, kcGaBhu, kcDaDha),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Ge'Dha: [%i]  Zo'Kho: [%i]  Pallas: [%i]  Alkyoneus: [%i]  Ixtab: [%i]  Hakutaku: [%i]  Friar Rush: [%i]  Sozu Bilberry: [%i]", kcGeDha, kcZoKho, kcPallas, kcAlkyoneus, kcIxtab, kcHakutaku, kcFriarRush, kcBilberry),tpz.msg.channel.SYSTEM_3)
		player:PrintToPlayer(string.format("  Tonberry Pontifex: [%i]  Ogama: [%i]", kcPontifex, kcOgama),tpz.msg.channel.SYSTEM_3)
	end
end